version: "3.8"
services:
  prod:
    image: podsumer
    container_name: podsumer
    build:
      context: .
    networks:
      - default
    ports:
      - 3095:3094
networks:
  backplane:
    driver: bridge

