version: "3.8"
services:
  php:
    image: podsumer
    container_name: php
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-podsumer.conf
      - ./:/opt/podsumer
    build:
      context: .
    networks:
      - backplane
  web:
    image: caddy:2.7.4-alpine
    container_name: web
    ports:
      - 8433:8433
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/opt/podsumer
    networks:
      - backplane
      - default
networks:
  backplane:
    driver: bridge

