version: "3.8"
services:
  podsumer:
    image: podsumer
    container_name: podsumer
    build:
      context: .
    volumes:
      - ./:/opt/podsumer
    networks:
      - default
    ports:
      - 3095:3094
networks:
  backplane:
    driver: bridge

