name: PHPUnit Test Coverage

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 10.5-dev
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-html
        env:
          XDEBUG_MODE: coverage
